extends Node
@warning_ignore_start("unsafe_cast", "unsafe_call_argument", "unsafe_method_access", "unsafe_property_access")
## Signal bus (autoload "Events"). Systems emit, stats/killfeed/audio/UI connect.
## Systems never call UI directly.

@warning_ignore_start("unused_signal")
signal projectile_launch(player_id: int, ammo: String, pos: Vector3, velocity: Vector3)
signal projectile_impact(player_id: int, ammo: String, pos: Vector3, speed: float)
signal part_break(pos: Vector3, material: String, size: float)
signal building_destroyed(structure_kind: String, owner_id: int, source: Dictionary)
signal settler_hit(settler_name: String, owner_id: int, source: Dictionary, launched: bool)
signal settler_killed(settler_name: String, owner_id: int, source: Dictionary)
signal catapult_destroyed(owner_id: int, source: Dictionary, reason: String)
signal fire_started(pos: Vector3, source: Dictionary)
signal fire_out(pos: Vector3, by_water: bool)
signal explosion(pos: Vector3, radius: float, max_damage: float, source: Dictionary)
signal turn_start(player_id: int)
signal turn_end(player_id: int)
signal player_eliminated(player_id: int)
signal game_over(winner_id: int)
signal weather_change(weather: String)
signal event_start(event_id: String)
signal language_changed()
signal quality_changed(tier: String)
# extra (UI / feel) signals
signal state_changed(state: int)
signal banner(text: String, kind: String)
signal toast(text: String)
signal gifts_changed
signal kill_feed(text: String)
signal shot_scored(player_id: int, score: float)
signal points_awarded(player_id: int, points: int, text: String)
signal wind_changed(wind: Vector2)
signal ammo_changed(player_id: int)
signal camera_shake(amount: float)
signal slowmo(scale_value: float, duration: float)
signal screen_flash(strength: float)
@warning_ignore_restore("unused_signal")
